.TH DIYSHIP "1" "2021" "NNB" "User Commands"
.SH NAME
DIYSHIP \- Cross-shell prompt framework
.SH DESCRIPTION
DIYship is a cross-shell prompt framework that let you write your prompt with any programing language for any shell.
.SH ENVIRONMENT VARIABLES
\fBDIYSHIP_COMMAND_LEFT\fR
Set command to print left prompt.
\fBDIYSHIP_COMMAND_RIGHT\fR
Set command to print right prompt.
.SH REPORTING BUGS
Report bugs to https://github.com/info-mono/diyship/issues
